"""empty message

Revision ID: 15036b97c36f
Revises: dbc84ed7ad51
Create Date: 2020-03-13 16:05:18.122881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15036b97c36f'
down_revision = 'dbc84ed7ad51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mobile_multiplatform',
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mobile_no', sa.String(length=50), nullable=True),
    sa.Column('user', sa.String(length=50), nullable=True),
    sa.Column('channel', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nik_multiplatform',
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nik', sa.String(length=50), nullable=True),
    sa.Column('user', sa.String(length=50), nullable=True),
    sa.Column('channel', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nik_multiplatform')
    op.drop_table('mobile_multiplatform')
    # ### end Alembic commands ###
