"""empty message

Revision ID: 17dada34bcc3
Revises: 15036b97c36f
Create Date: 2020-03-13 17:57:00.464945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17dada34bcc3'
down_revision = '15036b97c36f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mobile_multiplatform', sa.Column('day', sa.Date(), nullable=True))
    op.add_column('nik_multiplatform', sa.Column('day', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nik_multiplatform', 'day')
    op.drop_column('mobile_multiplatform', 'day')
    # ### end Alembic commands ###
