"""empty message

Revision ID: 1a2a1c33df3c
Revises: bd9a723ebaaf
Create Date: 2020-03-16 16:06:09.450826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a2a1c33df3c'
down_revision = 'bd9a723ebaaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nik_check',
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('nik', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('province', sa.String(length=50), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('district', sa.String(length=50), nullable=True),
    sa.Column('village', sa.String(length=50), nullable=True),
    sa.Column('work', sa.String(length=50), nullable=True),
    sa.Column('religion', sa.String(length=50), nullable=True),
    sa.Column('date_of_birth', sa.String(length=50), nullable=True),
    sa.Column('marital_status', sa.String(length=50), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('channel', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('nik')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nik_check')
    # ### end Alembic commands ###
