"""empty message

Revision ID: 252193d8166c
Revises: f7b6422865b8
Create Date: 2020-03-12 10:37:14.330218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '252193d8166c'
down_revision = 'f7b6422865b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('accesskey', sa.String(length=30), nullable=False),
    sa.Column('secretkey', sa.String(length=30), nullable=True),
    sa.Column('username', sa.String(length=20), nullable=True),
    sa.Column('password', sa.String(length=20), nullable=True),
    sa.Column('balance', sa.DECIMAL(precision=11, scale=3), nullable=True),
    sa.Column('extend_balance', sa.DECIMAL(precision=6, scale=2), nullable=True),
    sa.Column('email', sa.String(length=25), nullable=True),
    sa.Column('phone', sa.String(length=25), nullable=True),
    sa.PrimaryKeyConstraint('accesskey'),
    sa.UniqueConstraint('secretkey')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
