"""empty message

Revision ID: 3da6782e74bf
Revises: 51f43776d21f
Create Date: 2020-03-17 15:17:56.273693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3da6782e74bf'
down_revision = '51f43776d21f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nik_mobile_check',
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('nik', sa.String(length=20), nullable=False),
    sa.Column('mobile_no', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('nik')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nik_mobile_check')
    # ### end Alembic commands ###
