"""empty message

Revision ID: 51f43776d21f
Revises: 93f2900830a2
Create Date: 2020-03-17 10:03:03.832337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51f43776d21f'
down_revision = '93f2900830a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mobile_online',
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('mobile_no', sa.String(length=50), nullable=False),
    sa.Column('online', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('mobile_no')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mobile_online')
    # ### end Alembic commands ###
