"""empty message

Revision ID: 5270ea23b889
Revises: 
Create Date: 2020-03-12 10:30:00.966673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5270ea23b889'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('black_list',
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nik', sa.String(length=50), nullable=True),
    sa.Column('mobile_no', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('hitReason', sa.String(length=100), nullable=True, comment='OVERDUE_DAYS_BETWEEN_60_TO_90 or OVERDUE_DAYS_MORE_THAN_90'),
    sa.Column('channel', sa.String(length=10), nullable=True),
    sa.Column('eventtime', sa.String(length=10), nullable=True),
    sa.Column('response', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('accesskey', sa.String(length=30), nullable=False),
    sa.Column('secretkey', sa.String(length=30), nullable=True),
    sa.Column('username', sa.String(length=20), nullable=True),
    sa.Column('password', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=25), nullable=True),
    sa.Column('phone', sa.String(length=25), nullable=True),
    sa.PrimaryKeyConstraint('accesskey'),
    sa.UniqueConstraint('secretkey')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('black_list')
    # ### end Alembic commands ###
