"""empty message

Revision ID: 9181d6ef412b
Revises: 1a2a1c33df3c
Create Date: 2020-03-16 16:36:03.247201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9181d6ef412b'
down_revision = '1a2a1c33df3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nik_check', sa.Column('address', sa.String(length=250), nullable=True))
    op.add_column('nik_check', sa.Column('gender', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nik_check', 'gender')
    op.drop_column('nik_check', 'address')
    # ### end Alembic commands ###
