"""empty message

Revision ID: bd9a723ebaaf
Revises: 17dada34bcc3
Create Date: 2020-03-13 18:06:55.478056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd9a723ebaaf'
down_revision = '17dada34bcc3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'mobile_multiplatform', ['mobile_no', 'user', 'day'])
    op.create_unique_constraint(None, 'nik_multiplatform', ['nik', 'user', 'day'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'nik_multiplatform', type_='unique')
    op.drop_constraint(None, 'mobile_multiplatform', type_='unique')
    # ### end Alembic commands ###
