"""empty message

Revision ID: dbc84ed7ad51
Revises: 252193d8166c
Create Date: 2020-03-13 13:35:49.164409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbc84ed7ad51'
down_revision = '252193d8166c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mobile_multiplatform',
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mobile_no', sa.String(length=50), nullable=True),
    sa.Column('user', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nik_multiplatform',
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nik', sa.String(length=50), nullable=True),
    sa.Column('user', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nik_multiplatform')
    op.drop_table('mobile_multiplatform')
    # ### end Alembic commands ###
