"""empty message

Revision ID: f7b6422865b8
Revises: 5270ea23b889
Create Date: 2020-03-12 10:34:51.235759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7b6422865b8'
down_revision = '5270ea23b889'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('accesskey', sa.String(length=30), nullable=False),
    sa.Column('secretkey', sa.String(length=30), nullable=True),
    sa.Column('username', sa.String(length=20), nullable=True),
    sa.Column('password', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=25), nullable=True),
    sa.Column('phone', sa.String(length=25), nullable=True),
    sa.PrimaryKeyConstraint('accesskey'),
    sa.UniqueConstraint('secretkey')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
